---
- name: Include variables
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}-var.yml"
- name: Test version
  ansible.builtin.shell:
    cmd: oscap --version | head -1 | awk '{print $6}'
  register: version
  failed_when: false
  changed_when: version.stdout != oscap_version
- name: Build oscap
  when: version.changed and true
  block:
    - name: Include task
      ansible.builtin.include_tasks:
        file: "{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}.yml"
    - name: Clone oscap project
      ansible.builtin.git:
        repo: https://github.com/OpenSCAP/openscap.git
        dest: /tmp/openscap
        version: "{{ oscap_version }}"
        recursive: true
        force: true
    - name: Cmake
      ansible.builtin.shell:
        cmd: cmake .. -DCMAKE_INSTALL_PREFIX=/usr
        chdir: /tmp/openscap/build
      register: my_output
      changed_when: my_output.rc != 0
      tags:
        - skip_ansible_lint
    - name: Build OpenScap
      ansible.builtin.shell:
        cmd: make install
        chdir: /tmp/openscap/build
      become: true
      register: my_output
      changed_when: my_output.rc != 0
      tags:
        - skip_ansible_lint
    - name: Install
      ansible.builtin.shell:
        cmd: make install
        chdir: /tmp/openscap/build
      become: true
      register: my_output
      changed_when: my_output.rc != 0
      tags:
        - skip_ansible_lint
- name: Create folder to put ComplianceAsCode project
  ansible.builtin.file:
    mode: "0755"
    owner: root
    path: "{{ item }}"
    state: directory
  become: true
  with_items:
    - /opt/openscap-content
    - /tmp/openscap-reports
- name: Test folder existence
  ansible.builtin.lineinfile:
    name: /opt/openscap-content/ubuntu2204-script-standard.sh
    regex: "# Benchmark Version:  {{ content_version }}"
    line: "# Benchmark Version:  {{ content_version }}"
    state: present
  register: test_content
  ignore_errors: true
  become: true
- name: Install Content Block
  when: install_content and (test_content.changed or 'rc' in test_content)
  block:
    - name: Unzip ComplianceAsCode project
      ansible.builtin.unarchive:
        src: https://github.com/ComplianceAsCode/content/releases/download/v{{ content_version }}/scap-security-guide-{{ content_version }}.zip
        dest: /opt/openscap-content/
        remote_src: true
        extra_opts: -j
      become: true
- name: Scan
  when: scan
  block:
    - name: Scan
      ansible.builtin.shell:
        cmd: oscap xccdf eval --fetch-remote-resources --profile {{ openscap_profile }} --results-arf /tmp/openscap-reports/arf-{{ ansible_distribution | lower }}-{{
          ansible_distribution_major_version }}.xml --report /tmp/openscap-reports/report-{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version
          }}.html /opt/openscap-content/{{ openscap_security_policy }}
      become: true
      register: result
      failed_when: result.rc == 1
      changed_when: false
      tags:
        - skip_ansible_lint
    - name: Get reports
      ansible.builtin.fetch:
        src: "{{ item }}"
        dest: ./
        flat: true
      become: true
      with_items:
        - /tmp/openscap-reports/report-{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.html
        - /tmp/openscap-reports/arf-{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.xml
