---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: stephrobert_${image:-debian}-${tag:-latest}
    image: ${image:-debian}:${tag:-latest}
    dockerfile: Dockerfile.j2
    tty: True
    privileged: True
    pre_build_image: False
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    stop_signal: "SIGRTMIN+3"
    capabilities:
      - SYS_ADMIN
      - SYS_TIME
      - LINUX_IMMUTABLE
    command: "/lib/systemd/systemd"
provisioner:
  name: ansible

verifier:
  name: testinfra

lint:
  set -e
  yamllint .
  ansible-lint
  flake8

scenario:
  test_sequence:
    - destroy
    - create
    - converge
    # - idempotence
    - lint
    - verify