---
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: ubuntu-openscap
    image: ubuntu_ansible
    memory: 2048
    cpus: 3
    ssh_user: ansible
provisioner:
  name: ansible

verifier:
  name: testinfra

lint:
  set -e
  yamllint .
  ansible-lint
  flake8

scenario:
  test_sequence:
    - destroy
    - create
    - converge
    # - idempotence
    - lint
    - verify